extern class Camera extends Entity {}
extern class Texture {}
extern class Entity {}
extern class Channel {}
extern class Material {}
extern class Font {}
extern class Control {}
extern class Light extends Entity {}
extern class Memblock {}
extern class Mesh {}
extern class Pixmap {}
extern class Surface {}
extern class Model extends Entity {}
extern class Sound {}
extern class Sprite extends Entity {}
extern class Terrain extends Entity {}

@:native("_G") extern class Cs {
	public static inline final TRUE = 1;
	public static inline final FALSE = 0;
	public static inline final COLOR_RED = -65536;
	public static inline final COLOR_GREEN = -16711936;
	public static inline final COLOR_BLUE = -16776961;
	public static inline final COLOR_CYAN = -16711681;
	public static inline final COLOR_MAGENTA = -65281;
	public static inline final COLOR_YELLOW = -256;
	public static inline final COLOR_BLACK = -16777216;
	public static inline final COLOR_WHITE = -1;
	public static inline final COLOR_GRAY = -8355712;
	public static inline final COLOR_LIGHTGRAY = -4210753;
	public static inline final COLOR_DARKGRAY = -12566464;
	public static inline final COLOR_ORANGE = -23296;
	public static inline final COLOR_BROWN = -7650029;
	public static inline final COLLISION_NONE = 0;
	public static inline final COLLISION_BOX = 1;
	public static inline final COLLISION_MESH = 2;
	public static inline final COLLISION_OCTREE = 3;
	public static inline final ENTITY_EMPTY = 0;
	public static inline final ENTITY_SPRITE = 1;
	public static inline final ENTITY_CAMERA = 2;
	public static inline final ENTITY_EMITTER = 3;
	public static inline final ENTITY_LIGHT = 4;
	public static inline final ENTITY_MESH = 5;
	public static inline final ENTITY_MESH_OCTREE = 6;
	public static inline final ENTITY_TERRAIN = 7;
	public static inline final ENTITY_WATER = 8;
	public static inline final CONTROL_BUTTON = 1;
	public static inline final CONTROL_CHECKBOX = 2;
	public static inline final CONTROL_COMBOBOX = 3;
	public static inline final CONTROL_EDITBOX = 4;
	public static inline final CONTROL_IMAGE = 5;
	public static inline final CONTROL_LISTBOX = 6;
	public static inline final CONTROL_MENU = 7;
	public static inline final CONTROL_SCROLLBAR = 8;
	public static inline final CONTROL_TABBAR = 9;
	public static inline final CONTROL_TEXT = 10;
	public static inline final CONTROL_TOOLBAR = 11;
	public static inline final CONTROL_WINDOW = 12;
	public static inline final CONTROL_LOSTFOCUS = 0;
	public static inline final CONTROL_ENTER = 1;
	public static inline final CONTROL_EXIT = 2;
	public static inline final CONTROL_ACTION = 3;
	public static inline final EDITBOX_SIMPLE = 0;
	public static inline final EDITBOX_PASSWORD = 1;
	public static inline final EDITBOX_MULTILINE = 2;
	public static inline final BUTTON_LEFT = 1;
	public static inline final BUTTON_RIGHT = 2;
	public static inline final BUTTON_MIDDLE = 3;
	public static inline final KEY_LBUTTON = 0x01;
	public static inline final KEY_RBUTTON = 0x02;
	public static inline final KEY_CANCEL = 0x03;
	public static inline final KEY_MBUTTON = 0x04;
	public static inline final KEY_XBUTTON1 = 0x05;
	public static inline final KEY_XBUTTON2 = 0x06;
	public static inline final KEY_BACK = 0x08;
	public static inline final KEY_TAB = 0x09;
	public static inline final KEY_CLEAR = 0x0C;
	public static inline final KEY_RETURN = 0x0D;
	public static inline final KEY_ENTER = 0x0D;
	public static inline final KEY_SHIFT = 0x10;
	public static inline final KEY_CONTROL = 0x11;
	public static inline final KEY_MENU = 0x12;
	public static inline final KEY_PAUSE = 0x13;
	public static inline final KEY_CAPITAL = 0x14;
	public static inline final KEY_KANA = 0x15;
	public static inline final KEY_HANGUEL = 0x15;
	public static inline final KEY_HANGUL = 0x15;
	public static inline final KEY_JUNJA = 0x17;
	public static inline final KEY_FINAL = 0x18;
	public static inline final KEY_HANJA = 0x19;
	public static inline final KEY_KANJI = 0x19;
	public static inline final KEY_ESC = 0x1B;
	public static inline final KEY_ESCAPE = 0x1B;
	public static inline final KEY_CONVERT = 0x1C;
	public static inline final KEY_NONCONVERT = 0x1D;
	public static inline final KEY_ACCEPT = 0x1E;
	public static inline final KEY_MODECHANGE = 0x1F;
	public static inline final KEY_SPACE = 0x20;
	public static inline final KEY_PRIOR = 0x21;
	public static inline final KEY_NEXT = 0x22;
	public static inline final KEY_END = 0x23;
	public static inline final KEY_HOME = 0x24;
	public static inline final KEY_LEFT = 0x25;
	public static inline final KEY_UP = 0x26;
	public static inline final KEY_RIGHT = 0x27;
	public static inline final KEY_DOWN = 0x28;
	public static inline final KEY_SELECT = 0x29;
	public static inline final KEY_PRINT = 0x2A;
	public static inline final KEY_EXECUT = 0x2B;
	public static inline final KEY_SNAPSHOT = 0x2C;
	public static inline final KEY_INSERT = 0x2D;
	public static inline final KEY_DELETE = 0x2E;
	public static inline final KEY_HELP = 0x2F;
	public static inline final KEY_0 = 0x30;
	public static inline final KEY_1 = 0x31;
	public static inline final KEY_2 = 0x32;
	public static inline final KEY_3 = 0x33;
	public static inline final KEY_4 = 0x34;
	public static inline final KEY_5 = 0x35;
	public static inline final KEY_6 = 0x36;
	public static inline final KEY_7 = 0x37;
	public static inline final KEY_8 = 0x38;
	public static inline final KEY_9 = 0x39;
	public static inline final KEY_A = 0x41;
	public static inline final KEY_B = 0x42;
	public static inline final KEY_C = 0x43;
	public static inline final KEY_D = 0x44;
	public static inline final KEY_E = 0x45;
	public static inline final KEY_F = 0x46;
	public static inline final KEY_G = 0x47;
	public static inline final KEY_H = 0x48;
	public static inline final KEY_I = 0x49;
	public static inline final KEY_J = 0x4A;
	public static inline final KEY_K = 0x4B;
	public static inline final KEY_L = 0x4C;
	public static inline final KEY_M = 0x4D;
	public static inline final KEY_N = 0x4E;
	public static inline final KEY_O = 0x4F;
	public static inline final KEY_P = 0x50;
	public static inline final KEY_Q = 0x51;
	public static inline final KEY_R = 0x52;
	public static inline final KEY_S = 0x53;
	public static inline final KEY_T = 0x54;
	public static inline final KEY_U = 0x55;
	public static inline final KEY_V = 0x56;
	public static inline final KEY_W = 0x57;
	public static inline final KEY_X = 0x58;
	public static inline final KEY_Y = 0x59;
	public static inline final KEY_Z = 0x5A;
	public static inline final KEY_LWIN = 0x5B;
	public static inline final KEY_RWIN = 0x5C;
	public static inline final KEY_APPS = 0x5D;
	public static inline final KEY_SLEEP = 0x5F;
	public static inline final KEY_NUMPAD0 = 0x60;
	public static inline final KEY_NUMPAD1 = 0x61;
	public static inline final KEY_NUMPAD2 = 0x62;
	public static inline final KEY_NUMPAD3 = 0x63;
	public static inline final KEY_NUMPAD4 = 0x64;
	public static inline final KEY_NUMPAD5 = 0x65;
	public static inline final KEY_NUMPAD6 = 0x66;
	public static inline final KEY_NUMPAD7 = 0x67;
	public static inline final KEY_NUMPAD8 = 0x68;
	public static inline final KEY_NUMPAD9 = 0x69;
	public static inline final KEY_MULTIPLY = 0x6A;
	public static inline final KEY_ADD = 0x6B;
	public static inline final KEY_SEPARATOR = 0x6C;
	public static inline final KEY_SUBTRACT = 0x6D;
	public static inline final KEY_DECIMAL = 0x6E;
	public static inline final KEY_DIVIDE = 0x6F;
	public static inline final KEY_F1 = 0x70;
	public static inline final KEY_F2 = 0x71;
	public static inline final KEY_F3 = 0x72;
	public static inline final KEY_F4 = 0x73;
	public static inline final KEY_F5 = 0x74;
	public static inline final KEY_F6 = 0x75;
	public static inline final KEY_F7 = 0x76;
	public static inline final KEY_F8 = 0x77;
	public static inline final KEY_F9 = 0x78;
	public static inline final KEY_F10 = 0x79;
	public static inline final KEY_F11 = 0x7A;
	public static inline final KEY_F12 = 0x7B;
	public static inline final KEY_F13 = 0x7C;
	public static inline final KEY_F14 = 0x7D;
	public static inline final KEY_F15 = 0x7E;
	public static inline final KEY_F16 = 0x7F;
	public static inline final KEY_F17 = 0x80;
	public static inline final KEY_F18 = 0x81;
	public static inline final KEY_F19 = 0x82;
	public static inline final KEY_F20 = 0x83;
	public static inline final KEY_F21 = 0x84;
	public static inline final KEY_F22 = 0x85;
	public static inline final KEY_F23 = 0x86;
	public static inline final KEY_F24 = 0x87;
	public static inline final KEY_NUMLOCK = 0x90;
	public static inline final KEY_SCROLL = 0x91;
	public static inline final KEY_LSHIFT = 0xA0;
	public static inline final KEY_RSHIFT = 0xA1;
	public static inline final KEY_LCONTROL = 0xA2;
	public static inline final KEY_RCONTROL = 0xA3;
	public static inline final KEY_LMENU = 0xA4;
	public static inline final KEY_RMENU = 0xA5;
	public static inline final KEY_COMMA = 0xBC;
	public static inline final KEY_PLUS = 0xBB;
	public static inline final KEY_MINUS = 0xBD;
	public static inline final KEY_PERIOD = 0xBE;
	public static inline final KEY_ATTN = 0xF6;
	public static inline final KEY_CRSEL = 0xF7;
	public static inline final KEY_EXSEL = 0xF8;
	public static inline final KEY_EREOF = 0xF9;
	public static inline final KEY_PLAY = 0xFA;
	public static inline final KEY_ZOOM = 0xFB;
	public static inline final KEY_PA1 = 0xFD;
	public static inline final KEY_OEM_CLEAR = 0xFE;
	public static inline final LIGHT_DIRECTIONAL = 0;
	public static inline final LIGHT_POINT = 1;
	public static inline final LIGHT_SPOT = 2;
	public static inline final MATERIAL_SOLID = 0;
	public static inline final MATERIAL_LIGHTMAP = 1;
	public static inline final MATERIAL_LIGHTMAP2X = 2;
	public static inline final MATERIAL_LIGHTMAP4X = 3;
	public static inline final MATERIAL_DETAIL = 4;
	public static inline final MATERIAL_ADD = 5;
	public static inline final MATERIAL_ALPHA = 6;
	public static inline final MATERIAL_VERTEXALPHA = 7;
	public static inline final MATERIAL_MASKED = 8;
	public static inline final MATERIAL_SPHERE = 9;
	public static inline final MATERIAL_REFLECTION = 10;
	public static inline final MATERIAL_NORMAL = 11;
	public static inline final MATERIAL_NORMALADD = 12;
	public static inline final MATERIAL_PARALLAX = 13;
	public static inline final MATERIAL_PARALLAXADD = 14;
	public static inline final RENDER_FILLED = 0;
	public static inline final RENDER_WIREFRAME = 1;
	public static inline final RENDER_POINTCLOUD = 2;
	public static inline final LIGHTING_DISABLED = 0;
	public static inline final LIGHTING_GOURAUD = 1;
	public static inline final LIGHTING_FLAT = 2;
	public static inline final FILTER_DISABLED = 0;
	public static inline final FILTER_BILINEAR = 1;
	public static inline final FILTER_TRILINEAR = 2;
	public static inline final FILTER_ANISOTROPIC = 3;
	public static inline final FLAG_LIGHTING = 1;
	public static inline final FLAG_FOG = 2;
	public static inline final FLAG_ZREAD = 4;
	public static inline final FLAG_ZWRITE = 8;
	public static inline final FLAG_BACKFACECULLING = 16;
	public static inline final FLAG_NORMALIZE = 32;
	public static inline final FLAG_VERTEXCOLORS = 64;
	public static inline final FLAG_CLAMP = 128;
	public static inline final DRIVER_SOFTWAREFAST = 0;
	public static inline final DRIVER_SOFTWARE = 1;
	public static inline final DRIVER_OPENGL = 2;
	public static inline final DRIVER_DIRECT3D = 3;
	public static inline final SCREEN_FULLSCREEN = 1;
	public static inline final SCREEN_RESIZABLE = 2;
	public static inline final SCREEN_VSYNC = 4;
	public static inline final SURFACE_STANDARD = 0;
	public static inline final SURFACE_LIGHTMAP = 1;
	public static inline final SURFACE_TANGENTS = 2;
	public static inline final TEXTURE_MIPMAPS = 1;
	public static inline final TEXTURE_16BITS = 2;

	@:native("BitAnd") public static function bitAnd(a:Int, b:Int):Int;
	@:native("BitOr") public static function bitOr(a:Int, b:Int):Int;
	@:native("BitXor") public static function bitXor(a:Int, b:Int):Int;
	@:native("BitNot") public static function bitNot(val:Int):Int;
	@:native("Shl") public static function shl(val:Int, count:Int):Int;
	@:native("Shr") public static function shr(val:Int, count:Int):Int;
	@:native("CreateCamera") public static function createCamera():Camera;
	@:native("SetCameraActive") public static function setCameraActive(cam:Camera, active:Bool):Void;
	@:native("CameraActive") public static function cameraActive(cam:Camera):Bool;
	@:native("SetCameraViewport") public static function setCameraViewport(cam:Camera, x:Int, y:Int, width:Int, height:Int):Void;
	@:native("CameraViewportX") public static function cameraViewportX(cam:Camera):Int;
	@:native("CameraViewportY") public static function cameraViewportY(cam:Camera):Int;
	@:native("CameraViewportWidth") public static function cameraViewportWidth(cam:Camera):Int;
	@:native("CameraViewportHeight") public static function cameraViewportHeight(cam:Camera):Int;
	@:native("SetCameraClearMode") public static function setCameraClearMode(cam:Camera, clear_color:Bool, clear_depth:Bool):Void;
	@:native("CameraClearColorEnabled") public static function cameraClearColorEnabled(cam:Camera):Bool;
	@:native("CameraClearDepthEnabled") public static function cameraClearDepthEnabled(cam:Camera):Bool;
	@:native("SetCameraClearColor") public static function setCameraClearColor(cam:Camera, color:Int):Void;
	@:native("CameraClearColor") public static function cameraClearColor(cam:Camera):Int;
	@:native("SetCameraRenderTarget") public static function setCameraRenderTarget(cam:Camera, target:Texture):Void;
	@:native("CameraRenderTarget") public static function cameraRenderTarget(cam:Camera):Texture;
	@:native("SetCameraRange") public static function setCameraRange(cam:Camera, near_:Float, far_:Float):Void;
	@:native("CameraNearRange") public static function cameraNearRange(cam:Camera):Float;
	@:native("CameraFarRange") public static function cameraFarRange(cam:Camera):Float;
	@:native("SetCameraAspectRatio") public static function setCameraAspectRatio(cam:Camera, ratio:Float):Void;
	@:native("CameraAspectRatio") public static function cameraAspectRatio(cam:Camera):Float;
	@:native("SetCameraFOV") public static function setCameraFOV(cam:Camera, fov:Float):Void;
	@:native("CameraFOV") public static function cameraFOV(cam:Camera):Float;
	@:native("SetCameraOrtho") public static function setCameraOrtho(cam:Camera, enable:Bool):Void;
	@:native("CameraOrtho") public static function cameraOrtho(cam:Camera):Bool;
	@:native("PickEntity") public static function pickEntity(camera:Camera, x:Int, y:Int, group:Int):Entity;
	@:native("StopChannel") public static function stopChannel(channel:Channel):Void;
	@:native("PauseChannel") public static function pauseChannel(channel:Channel):Void;
	@:native("ResumeChannel") public static function resumeChannel(channel:Channel):Void;
	@:native("SetChannel3DPosition") public static function setChannel3DPosition(channel:Channel, x:Float, y:Float, z:Float):Void;
	@:native("SetChannelRadius") public static function setChannelRadius(channel:Channel, radius:Float):Void;
	@:native("SetChannelPitch") public static function setChannelPitch(channel:Channel, pitch:Float):Void;
	@:native("SetChannelVolume") public static function setChannelVolume(channel:Channel, volume:Float):Void;
	@:native("SetChannelPan") public static function setChannelPan(channel:Channel, pan:Float):Void;
	@:native("ChannelPlaying") public static function channelPlaying(channel:Channel):Bool;
	@:native("RGB") public static function rgb(red:Int, green:Int, blue:Int):Int;
	@:native("RGBA") public static function rgba(red:Int, green:Int, blue:Int, alpha:Int):Int;
	@:native("RGBF") public static function rgbF(red:Float, green:Float, blue:Float):Int;
	@:native("RGBAF") public static function rgbaF(red:Float, green:Float, blue:Float, alpha:Float):Int;
	@:native("RedVal") public static function redVal(color:Int):Int;
	@:native("GreenVal") public static function greenVal(color:Int):Int;
	@:native("BlueVal") public static function blueVal(color:Int):Int;
	@:native("AlphaVal") public static function alphaVal(color:Int):Int;
	@:native("RedValF") public static function redValF(color:Int):Float;
	@:native("GreenValF") public static function greenValF(color:Int):Float;
	@:native("BlueValF") public static function blueValF(color:Int):Float;
	@:native("AlphaValF") public static function alphaValF(color:Int):Float;
	@:native("FadeColor") public static function fadeColor(color:Int, new_alpha:Int):Int;
	@:native("MultiplyColor") public static function multiplyColor(color:Int, factor:Float):Int;
	@:native("SwapColor") public static function swapColor(color:Int):Int;
	@:native("DeltaTime") public static function deltaTime():Float;
	@:native("Millisecs") public static function millisecs():Int;
	@:native("Exit") public static function exit(code:Int):Void;
	@:native("System") public static function system(command:String):Int;
	@:native("AddZip") public static function addZip(filename:String):Bool;
	@:native("DirContents") public static function dirContents(dir:String):String;
	@:native("ChangeDir") public static function changeDir(dir:String):Void;
	@:native("CurrentDir") public static function currentDir():String;
	@:native("CreateEntity") public static function createEntity():Entity;
	@:native("FreeEntity") public static function freeEntity(entity:Entity):Void;
	@:native("EntityType") public static function entityType(entity:Entity):Int;
	@:native("SetEntityName") public static function setEntityName(entity:Entity, name:String):Void;
	@:native("EntityName") public static function entityName(entity:Entity):String;
	@:native("SetEntityVisible") public static function setEntityVisible(entity:Entity, visible:Bool):Void;
	@:native("EntityVisible") public static function entityVisible(entity:Entity):Bool;
	@:native("SetEntityParent") public static function setEntityParent(entity:Entity, parent:Entity):Void;
	@:native("EntityParent") public static function entityParent(entity:Entity):Entity;
	@:native("EntityNumChildren") public static function entityNumChildren(entity:Entity):Int;
	@:native("EntityChild") public static function entityChild(entity:Entity, index:Int):Entity;
	@:native("SetEntityPosition") public static function setEntityPosition(entity:Entity, x:Float, y:Float, z:Float):Void;
	@:native("MoveEntity") public static function moveEntity(entity:Entity, x:Float, y:Float, z:Float):Void;
	@:native("SlideEntity") public static function slideEntity(entity:Entity, x:Float, y:Float, z:Float, radiusX:Float, radiusY:Float, radiusZ:Float, group:Int):Entity;
	@:native("TranslateEntity") public static function translateEntity(entity:Entity, x:Float, y:Float, z:Float):Void;
	@:native("EntityX") public static function entityX(entity:Entity):Float;
	@:native("EntityY") public static function entityY(entity:Entity):Float;
	@:native("EntityZ") public static function entityZ(entity:Entity):Float;
	@:native("EntityLocalX") public static function entityLocalX(entity:Entity):Float;
	@:native("EntityLocalY") public static function entityLocalY(entity:Entity):Float;
	@:native("EntityLocalZ") public static function entityLocalZ(entity:Entity):Float;
	@:native("SetEntityRotation") public static function setEntityRotation(entity:Entity, pitch:Float, yaw:Float, roll:Float):Void;
	@:native("TurnEntity") public static function turnEntity(entity:Entity, pitch:Float, yaw:Float, roll:Float):Void;
	@:native("PointEntity") public static function pointEntity(entity:Entity, x:Float, y:Float, z:Float):Void;
	@:native("EntityPitch") public static function entityPitch(entity:Entity):Float;
	@:native("EntityYaw") public static function entityYaw(entity:Entity):Float;
	@:native("EntityRoll") public static function entityRoll(entity:Entity):Float;
	@:native("SetEntityScale") public static function setEntityScale(entity:Entity, x:Float, y:Float, z:Float):Void;
	@:native("EntityScaleX") public static function entityScaleX(entity:Entity):Float;
	@:native("EntityScaleY") public static function entityScaleY(entity:Entity):Float;
	@:native("EntityScaleZ") public static function entityScaleZ(entity:Entity):Float;
	@:native("EntityWidth") public static function entityWidth(entity:Entity):Float;
	@:native("EntityHeight") public static function entityHeight(entity:Entity):Float;
	@:native("EntityDepth") public static function entityDepth(entity:Entity):Float;
	@:native("EntityNumMaterials") public static function entityNumMaterials(entity:Entity):Int;
	@:native("EntityMaterial") public static function entityMaterial(entity:Entity, index:Int):Material;
	@:native("SetEntityCollision") public static function setEntityCollision(entity:Entity, type:Int, group:Int):Void;
	@:native("EntityCollision") public static function entityCollision(entity:Entity):Bool;
	@:native("EntityGroup") public static function entityGroup(entity:Entity):Int;
	@:native("EntityDistance") public static function entityDistance(entity:Entity, x:Float, y:Float, z:Float):Float;
	@:native("EntitySquareDistance") public static function entitySquareDistance(entity:Entity, x:Float, y:Float, z:Float):Float;
	@:native("LoadFont") public static function loadFont(filename:String):Font;
	@:native("FreeFont") public static function freeFont(font:Font):Void;
	@:native("DrawText") public static function drawText(font:Font, text:String, x:Int, y:Int, color:Int):Void;
	@:native("TextWidth") public static function textWidth(font:Font, text:String):Int;
	@:native("TextHeight") public static function textHeight(font:Font, text:String):Int;
	@:native("SetRenderTarget") public static function setRenderTarget(tex:Texture, clear:Bool, clearDepth:Bool, color:Int):Void;
	@:native("SetViewport") public static function setViewport(x:Int, y:Int, width:Int, height:Int):Void;
	@:native("DrawPoint") public static function drawPoint(x:Int, y:Int, color:Int):Void;
	@:native("DrawLine") public static function drawLine(x1:Int, y1:Int, x2:Int, y2:Int, color:Int):Void;
	@:native("DrawRect") public static function drawRect(x:Int, y:Int, width:Int, height:Int, color:Int):Void;
	@:native("Draw3DLine") public static function draw3DLine(x1:Float, y1:Float, z1:Float, x2:Float, y2:Float, z2:Float, color:Int):Void;
	@:native("CreateButton") public static function createButton(x:Int, y:Int, width:Int, height:Int, text:String, parent:Control):Control;
	@:native("CreateCheckBox") public static function createCheckBox(x:Int, y:Int, width:Int, height:Int, text:String, parent:Control):Control;
	@:native("CreateComboBox") public static function createComboBox(x:Int, y:Int, width:Int, height:Int, parent:Control):Control;
	@:native("CreateContextMenu") public static function createContextMenu(x:Int, y:Int, width:Int, height:Int, parent:Control):Control;
	@:native("CreateEditBox") public static function createEditBox(x:Int, y:Int, width:Int, height:Int, type:Int, parent:Control):Control;
	@:native("CreateImage") public static function createImage(x:Int, y:Int, width:Int, height:Int, texture:Texture, parent:Control):Control;
	@:native("CreateListBox") public static function createListBox(x:Int, y:Int, width:Int, height:Int, parent:Control):Control;
	@:native("CreateMenu") public static function createMenu(text:String, parent:Control):Control;
	@:native("CreateScrollbar") public static function createScrollbar(x:Int, y:Int, width:Int, height:Int, horizontal:Bool, max:Int, step:Int, parent:Control):Control;
	@:native("CreateTabbar") public static function createTabbar(x:Int, y:Int, width:Int, height:Int, parent:Control):Control;
	@:native("CreateText") public static function createText(x:Int, y:Int, width:Int, height:Int, text:String, border:Bool, parent:Control):Control;
	@:native("CreateToolbar") public static function createToolbar(parent:Control):Control;
	@:native("CreateWindow") public static function createWindow(x:Int, y:Int, width:Int, height:Int, modal:Bool, parent:Control):Control;
	@:native("FreeControl") public static function freeControl(control:Control):Void;
	@:native("ControlType") public static function controlType(control:Control):Int;
	@:native("SetControlEnabled") public static function setControlEnabled(control:Control, enabled:Bool):Void;
	@:native("ControlEnabled") public static function controlEnabled(control:Control):Bool;
	@:native("SetControlVisible") public static function setControlVisible(control:Control, visible:Bool):Void;
	@:native("ControlVisible") public static function controlVisible(control:Control):Bool;
	@:native("ControlParent") public static function controlParent(control:Control):Control;
	@:native("ControlNumChildren") public static function controlNumChildren(control:Control):Int;
	@:native("ControlChild") public static function controlChild(control:Control, index:Int):Control;
	@:native("SetControlShape") public static function setControlShape(control:Control, x:Int, y:Int, width:Int, height:Int):Void;
	@:native("ControlX") public static function controlX(control:Control):Int;
	@:native("ControlY") public static function controlY(control:Control):Int;
	@:native("ControlWidth") public static function controlWidth(control:Control):Int;
	@:native("ControlHeight") public static function controlHeight(control:Control):Int;
	@:native("SetControlText") public static function setControlText(control:Control, text:String):Void;
	@:native("ControlText") public static function controlText(control:Control):String;
	@:native("SetControlTooltip") public static function setControlTooltip(control:Control, tooltip:String):Void;
	@:native("ControlTooltip") public static function controlTooltip(control:Control):String;
	@:native("SetControlTexture") public static function setControlTexture(control:Control, texture:Texture, alpha:Bool):Void;
	@:native("SetControlFont") public static function setControlFont(control:Control, font:Font):Void;
	@:native("ControlFont") public static function controlFont(control:Control):Font;
	@:native("SetControlColor") public static function setControlColor(control:Control, color:Int):Void;
	@:native("ClearControlColor") public static function clearControlColor(control:Control):Void;
	@:native("ControlColor") public static function controlColor(control:Control):Int;
	@:native("SetControlChecked") public static function setControlChecked(control:Control, checked:Bool):Void;
	@:native("ControlChecked") public static function controlChecked(control:Control):Bool;
	@:native("SetControlValue") public static function setControlValue(control:Control, value:Int):Void;
	@:native("ControlValue") public static function controlValue(control:Control):Int;
	@:native("ControlId") public static function controlId(control:Control):Int;
	@:native("AddControlItem") public static function addControlItem(control:Control, text:String, id:Int):Int;
	@:native("ControlNumItems") public static function controlNumItems(control:Control):Int;
	@:native("SetControlItemEnabled") public static function setControlItemEnabled(control:Control, index:Int, enable:Bool):Void;
	@:native("ControlItemEnabled") public static function controlItemEnabled(control:Control, index:Int):Bool;
	@:native("SetControlItemChecked") public static function setControlItemChecked(control:Control, index:Int, check:Bool):Void;
	@:native("ControlItemChecked") public static function controlItemChecked(control:Control, index:Int):Bool;
	@:native("SelectControlItem") public static function selectControlItem(control:Control, index:Int):Void;
	@:native("SelectedControlItem") public static function selectedControlItem(control:Control):Int;
	@:native("SetControlItemText") public static function setControlItemText(control:Control, index:Int, text:String):Void;
	@:native("ControlItemText") public static function controlItemText(control:Control, index:Int):String;
	@:native("RemoveControlItem") public static function removeControlItem(control:Control, index:Int):Void;
	@:native("RemoveControlItems") public static function removeControlItems(control:Control):Void;
	@:native("AddMenuSeparator") public static function addMenuSeparator(menu:Control):Void;
	@:native("DrawGUI") public static function drawGUI():Void;
	@:native("PrepareNextGUIEvent") public static function prepareNextGUIEvent():Bool;
	@:native("GUIEventType") public static function guiEventType():Int;
	@:native("GUIEventControl") public static function guiEventControl():Control;
	@:native("GUIEventMenuId") public static function guiEventMenuId():Int;
	@:native("SetCursorVisible") public static function setCursorVisible(visible:Bool):Void;
	@:native("SetCursorPosition") public static function setCursorPosition(x:Int, y:Int):Void;
	@:native("CursorX") public static function cursorX():Int;
	@:native("CursorY") public static function cursorY():Int;
	@:native("CursorZ") public static function cursorZ():Int;
	@:native("ButtonDown") public static function buttonDown(button:Int):Bool;
	@:native("ButtonHit") public static function buttonHit(button:Int):Bool;
	@:native("KeyDown") public static function keyDown(key:Int):Bool;
	@:native("KeyHit") public static function keyHit(key:Int):Bool;
	@:native("NumJoysticks") public static function numJoysticks():Int;
	@:native("JoystickName") public static function joystickName(index:Int):String;
	@:native("NumJoystickAxes") public static function numJoystickAxes(index:Int):Int;
	@:native("NumJoystickButtons") public static function numJoystickButtons(index:Int):Int;
	@:native("JoystickButtonDown") public static function joystickButtonDown(index:Int, button:Int):Bool;
	@:native("JoystickAxis") public static function joystickAxis(index:Int, axis:Int):Float;
	@:native("CreateLight") public static function createLight(type:Int):Light;
	@:native("LightType") public static function lightType(light:Light):Int;
	@:native("SetLightDiffuse") public static function setLightDiffuse(light:Light, color:Int):Void;
	@:native("LightDiffuse") public static function lightDiffuse(light:Light):Int;
	@:native("SetLightAmbient") public static function setLightAmbient(light:Light, color:Int):Void;
	@:native("LightAmbient") public static function lightAmbient(light:Light):Int;
	@:native("SetLightSpecular") public static function setLightSpecular(light:Light, color:Int):Void;
	@:native("LightSpecular") public static function lightSpecular(light:Light):Int;
	@:native("SetLightCastShadows") public static function setLightCastShadows(light:Light, enable:Bool):Void;
	@:native("LightCastShadows") public static function lightCastShadows(light:Light):Bool;
	@:native("SetLightRadius") public static function setLightRadius(light:Light, radius:Float):Void;
	@:native("LightRadius") public static function lightRadius(light:Light):Float;
	@:native("SetLightAttenuation") public static function setLightAttenuation(light:Light, constant:Float, linear:Float, quadratic:Float):Void;
	@:native("LightConstantAttenuation") public static function lightConstantAttenuation(light:Light):Float;
	@:native("LightLinearAttenuation") public static function lightLinearAttenuation(light:Light):Float;
	@:native("LightQuadraticAttenuation") public static function lightQuadraticAttenuation(light:Light):Float;
	@:native("SetLightCone") public static function setLightCone(light:Light, inner:Float, outer:Float):Void;
	@:native("LightInnerCone") public static function lightInnerCone(light:Light):Float;
	@:native("LightOuterCone") public static function lightOuterCone(light:Light):Float;
	@:native("SetLightFalloff") public static function setLightFalloff(light:Light, falloff:Float):Void;
	@:native("LightFalloff") public static function lightFalloff(light:Light):Float;
	@:native("SetListener") public static function setListener(x:Float, y:Float, z:Float, yaw:Float):Void;
	@:native("LogInfo") public static function logInfo(msg:String):Void;
	@:native("SetMaterialTexture") public static function setMaterialTexture(material:Material, index:Int, texture:Texture):Void;
	@:native("MaterialTexture") public static function materialTexture(material:Material, index:Int):Texture;
	@:native("SetMaterialTextureTransform") public static function setMaterialTextureTransform(material:Material, index:Int, xoffset:Float, yoffset:Float, angle:Float, xscale:Float, yscale:Float):Void;
	@:native("SetMaterialType") public static function setMaterialType(material:Material, type:Int):Void;
	@:native("MaterialType") public static function materialType(material:Material):Int;
	@:native("SetMaterialDiffuse") public static function setMaterialDiffuse(material:Material, color:Int):Void;
	@:native("MaterialDiffuse") public static function materialDiffuse(material:Material):Int;
	@:native("SetMaterialEmissive") public static function setMaterialEmissive(material:Material, color:Int):Void;
	@:native("MaterialEmissive") public static function materialEmissive(material:Material):Int;
	@:native("SetMaterialAmbient") public static function setMaterialAmbient(material:Material, color:Int):Void;
	@:native("MaterialAmbient") public static function materialAmbient(material:Material):Int;
	@:native("SetMaterialSpecular") public static function setMaterialSpecular(material:Material, color:Int):Void;
	@:native("MaterialSpecular") public static function materialSpecular(material:Material):Int;
	@:native("SetMaterialShininess") public static function setMaterialShininess(material:Material, shininess:Float):Void;
	@:native("MaterialShininess") public static function materialShininess(material:Material):Float;
	@:native("SetMaterialRenderMode") public static function setMaterialRenderMode(material:Material, mode:Int):Void;
	@:native("MaterialRenderMode") public static function materialRenderMode(material:Material):Int;
	@:native("SetMaterialFilterMode") public static function setMaterialFilterMode(material:Material, mode:Int):Void;
	@:native("MaterialFilterMode") public static function materialFilterMode(material:Material):Int;
	@:native("SetMaterialLightingMode") public static function setMaterialLightingMode(material:Material, mode:Int):Void;
	@:native("MaterialLightingMode") public static function materialLightingMode(material:Material):Int;
	@:native("SetMaterialFlag") public static function setMaterialFlag(material:Material, flag:Int, enable:Bool):Void;
	@:native("MaterialFlag") public static function materialFlag(material:Material, flag:Int):Bool;
	@:native("Floor") public static function floor(val:Float):Float;
	@:native("Ceil") public static function ceil(val:Float):Float;
	@:native("Abs") public static function abs(val:Float):Float;
	@:native("Sqr") public static function sqr(val:Float):Float;
	@:native("Sin") public static function sin(val:Float):Float;
	@:native("Cos") public static function cos(val:Float):Float;
	@:native("Tan") public static function tan(val:Float):Float;
	@:native("ASin") public static function aSin(val:Float):Float;
	@:native("ACos") public static function aCos(val:Float):Float;
	@:native("ATan") public static function aTan(val:Float):Float;
	@:native("ATan2") public static function aTan2(x:Float, y:Float):Float;
	@:native("Exp") public static function exp(val:Float):Float;
	@:native("Pow") public static function pow(base:Float, exp:Float):Float;
	@:native("Log") public static function log(val:Float):Float;
	@:native("Log10") public static function log10(val:Float):Float;
	@:native("Min") public static function min(a:Float, b:Float):Float;
	@:native("Max") public static function max(a:Float, b:Float):Float;
	@:native("Clamp") public static function clamp(val:Float, min:Float, max:Float):Float;
	@:native("BoolToInt") public static function boolToInt(val:Bool):Int;
	@:native("Int") public static function int(val:Float):Int;
	@:native("Rand") public static function rand(min:Int, max:Int):Int;
	@:native("RandSeed") public static function randSeed(seed:Int):Void;
	@:native("Deg") public static function deg(rad:Float):Float;
	@:native("Rad") public static function rad(deg:Float):Float;
	@:native("Wrap") public static function wrap(val:Float, mod:Float):Float;
	@:native("PointX") public static function pointX():Float;
	@:native("PointY") public static function pointY():Float;
	@:native("PointZ") public static function pointZ():Float;
	@:native("NormalX") public static function normalX():Float;
	@:native("NormalY") public static function normalY():Float;
	@:native("NormalZ") public static function normalZ():Float;
	@:native("CreateMemblock") public static function createMemblock(size:Int):Memblock;
	@:native("LoadMemblock") public static function loadMemblock(filename:String):Memblock;
	@:native("SaveMemblock") public static function saveMemblock(memblock:Memblock, filename:String):Void;
	@:native("FreeMemblock") public static function freeMemblock(memblock:Memblock):Void;
	@:native("MemblockSize") public static function memblockSize(memblock:Memblock):Int;
	@:native("PokeByte") public static function pokeByte(memblock:Memblock, offset:Int, val:Int):Void;
	@:native("PokeShort") public static function pokeShort(memblock:Memblock, offset:Int, val:Int):Void;
	@:native("PokeInt") public static function pokeInt(memblock:Memblock, offset:Int, val:Int):Void;
	@:native("PokeFloat") public static function pokeFloat(memblock:Memblock, offset:Int, val:Float):Void;
	@:native("PokeString") public static function pokeString(memblock:Memblock, offset:Int, val:String):Void;
	@:native("PeekByte") public static function peekByte(memblock:Memblock, offset:Int):Int;
	@:native("PeekShort") public static function peekShort(memblock:Memblock, offset:Int):Int;
	@:native("PeekInt") public static function peekInt(memblock:Memblock, offset:Int):Int;
	@:native("PeekFloat") public static function peekFloat(memblock:Memblock, offset:Int):Float;
	@:native("PeekString") public static function peekString(memblock:Memblock, offset:Int):String;
	@:native("CreateConeMesh") public static function createConeMesh(segments:Int):Mesh;
	@:native("CreateCubeMesh") public static function createCubeMesh():Mesh;
	@:native("CreateCylinderMesh") public static function createCylinderMesh(segments:Int):Mesh;
	@:native("CreateMesh") public static function createMesh():Mesh;
	@:native("CreateQuadMesh") public static function createQuadMesh():Mesh;
	@:native("CreateSimpleCubeMesh") public static function createSimpleCubeMesh():Mesh;
	@:native("CreateSphereMesh") public static function createSphereMesh(segments:Int):Mesh;
	@:native("LoadMesh") public static function loadMesh(filename:String):Mesh;
	@:native("LoadTerrainMesh") public static function loadTerrainMesh(heightmap:Pixmap, pixmap:Pixmap, width:Float, height:Float, depth:Float):Mesh;
	@:native("FreeMesh") public static function freeMesh(mesh:Mesh):Void;
	@:native("SetMeshFPS") public static function setMeshFPS(mesh:Mesh, fps:Float):Void;
	@:native("MeshFPS") public static function meshFPS(mesh:Mesh):Float;
	@:native("MeshFrames") public static function meshFrames(mesh:Mesh):Int;
	@:native("MeshForFrame") public static function meshForFrame(mesh:Mesh, frame:Int):Mesh;
	@:native("NumSurfaces") public static function numSurfaces(mesh:Mesh):Int;
	@:native("MeshSurface") public static function meshSurface(mesh:Mesh, index:Int):Surface;
	@:native("UpdateMesh") public static function updateMesh(mesh:Mesh):Void;
	@:native("TranslateMesh") public static function translateMesh(mesh:Mesh, x:Float, y:Float, z:Float):Void;
	@:native("RotateMesh") public static function rotateMesh(mesh:Mesh, pitch:Float, yaw:Float, roll:Float):Void;
	@:native("ScaleMesh") public static function scaleMesh(mesh:Mesh, x:Float, y:Float, z:Float):Void;
	@:native("FlipMesh") public static function flipMesh(mesh:Mesh):Void;
	@:native("SetMeshColor") public static function setMeshColor(mesh:Mesh, color:Int):Void;
	@:native("UpdateMeshNormals") public static function updateMeshNormals(mesh:Mesh):Void;
	@:native("MeshWidth") public static function meshWidth(mesh:Mesh):Float;
	@:native("MeshHeight") public static function meshHeight(mesh:Mesh):Float;
	@:native("MeshDepth") public static function meshDepth(mesh:Mesh):Float;
	@:native("SaveMesh") public static function saveMesh(mesh:Mesh, filename:String):Bool;
	@:native("CreateConeModel") public static function createConeModel(segments:Int):Model;
	@:native("CreateCubeModel") public static function createCubeModel():Model;
	@:native("CreateCylinderModel") public static function createCylinderModel(segments:Int):Model;
	@:native("CreateModel") public static function createModel(mesh:Mesh):Model;
	@:native("CreateOctreeModel") public static function createOctreeModel(mesh:Mesh):Model;
	@:native("CreateQuadModel") public static function createQuadModel():Model;
	@:native("CreateSphereModel") public static function createSphereModel(segments:Int):Model;
	@:native("LoadModel") public static function loadModel(filename:String):Model;
	@:native("LoadOctreeModel") public static function loadOctreeModel(filename:String):Model;
	@:native("ModelMesh") public static function modelMesh(entity:Model):Mesh;
	@:native("SetModelCastShadows") public static function setModelCastShadows(entity:Model, enable:Bool):Void;
	@:native("ModelCastShadows") public static function modelCastShadows(entity:Model):Bool;
	@:native("SetModelLoop") public static function setModelLoop(entity:Model, loop:Bool):Void;
	@:native("ModelLoop") public static function modelLoop(entity:Model):Bool;
	@:native("SetModelFPS") public static function setModelFPS(entity:Model, fps:Float):Void;
	@:native("ModelFPS") public static function modelFPS(entity:Model):Float;
	@:native("SetModelFrame") public static function setModelFrame(entity:Model, frame:Float):Void;
	@:native("ModelFrame") public static function modelFrame(entity:Model):Float;
	@:native("SetModelFrames") public static function setModelFrames(entity:Model, first:Int, last:Int):Void;
	@:native("ModelFirstFrame") public static function modelFirstFrame(entity:Model):Int;
	@:native("ModelLastFrame") public static function modelLastFrame(entity:Model):Int;
	@:native("PlayMusic") public static function playMusic(filename:String, loop:Bool):Bool;
	@:native("StopMusic") public static function stopMusic():Void;
	@:native("PauseMusic") public static function pauseMusic():Void;
	@:native("ResumeMusic") public static function resumeMusic():Void;
	@:native("SetMusicVolume") public static function setMusicVolume(volume:Float):Void;
	@:native("MusicPlaying") public static function musicPlaying():Bool;
	@:native("CreatePixmap") public static function createPixmap(width:Int, height:Int):Pixmap;
	@:native("CreatePixmapFromTexture") public static function createPixmapFromTexture(texture:Texture):Pixmap;
	@:native("CreatePixmapFromScreen") public static function createPixmapFromScreen():Pixmap;
	@:native("LoadPixmap") public static function loadPixmap(filename:String):Pixmap;
	@:native("FreePixmap") public static function freePixmap(pixmap:Pixmap):Void;
	@:native("SavePixmap") public static function savePixmap(pixmap:Pixmap, filename:String):Void;
	@:native("ReadPixel") public static function readPixel(pixmap:Pixmap, x:Int, y:Int):Int;
	@:native("WritePixel") public static function writePixel(pixmap:Pixmap, x:Int, y:Int, color:Int):Void;
	@:native("PixmapWidth") public static function pixmapWidth(pixmap:Pixmap):Int;
	@:native("PixmapHeight") public static function pixmapHeight(pixmap:Pixmap):Int;
	@:native("SetDriver") public static function setDriver(driver:Int):Void;
	@:native("DriverName") public static function driverName():String;
	@:native("OpenScreen") public static function openScreen(width:Int, height:Int, depth:Int, flags:Int):Void;
	@:native("OpenScreenEx") public static function openScreenEx(width:Int, height:Int, depth:Int, flags:Int, samples:Int, win:Any):Void;
	@:native("CloseScreen") public static function closeScreen():Void;
	@:native("ClearScreen") public static function clearScreen(color:Int):Void;
	@:native("RefreshScreen") public static function refreshScreen():Void;
	@:native("SetScreenTitle") public static function setScreenTitle(caption:String):Void;
	@:native("SetScreenSize") public static function setScreenSize(width:Int, height:Int):Void;
	@:native("ScreenActive") public static function screenActive():Bool;
	@:native("ScreenShouldClose") public static function screenShouldClose():Bool;
	@:native("ScreenWidth") public static function screenWidth():Int;
	@:native("ScreenHeight") public static function screenHeight():Int;
	@:native("SetScreenFPS") public static function setScreenFPS(fps:Int):Void;
	@:native("ScreenFPS") public static function screenFPS():Int;
	@:native("ScreenNumModes") public static function screenNumModes():Int;
	@:native("ScreenModeWidth") public static function screenModeWidth(index:Int):Int;
	@:native("ScreenModeHeight") public static function screenModeHeight(index:Int):Int;
	@:native("ScreenModeDepth") public static function screenModeDepth(index:Int):Int;
	@:native("DesktopWidth") public static function desktopWidth():Int;
	@:native("DesktopHeight") public static function desktopHeight():Int;
	@:native("DesktopDepth") public static function desktopDepth():Int;
	@:native("MinimizeWindow") public static function minimizeWindow():Void;
	@:native("MaximizeWindow") public static function maximizeWindow():Void;
	@:native("RestoreWindow") public static function restoreWindow():Void;
	@:native("LoadSound") public static function loadSound(filename:String):Sound;
	@:native("FreeSound") public static function freeSound(sound:Sound):Void;
	@:native("PlaySound") public static function playSound(sound:Sound, loop:Bool):Channel;
	@:native("PlaySound3D") public static function playSound3D(sound:Sound, x:Float, y:Float, z:Float, radius:Float, loop:Bool):Channel;
	@:native("CreateSprite") public static function createSprite(texture:Texture, materialType:Int):Sprite;
	@:native("SetSpriteSize") public static function setSpriteSize(sprite:Sprite, width:Float, height:Float):Void;
	@:native("SpriteWidth") public static function spriteWidth(sprite:Sprite):Float;
	@:native("SpriteHeight") public static function spriteHeight(sprite:Sprite):Float;
	@:native("Val") public static function val(str:String):Int;
	@:native("ValF") public static function valF(str:String):Float;
	@:native("Str") public static function str(number:Int):String;
	@:native("StrF") public static function strF(number:Float):String;
	@:native("Left") public static function left(str:String, num:Int):String;
	@:native("Right") public static function right(str:String, num:Int):String;
	@:native("Mid") public static function mid(str:String, pos:Int, num:Int):String;
	@:native("Replace") public static function replace(str:String, find:String, replace:String):String;
	@:native("Find") public static function find(str:String, find:String, offset:Int):Int;
	@:native("Upper") public static function upper(str:String):String;
	@:native("Lower") public static function lower(str:String):String;
	@:native("Trim") public static function trim(str:String):String;
	@:native("Char") public static function char(code:Int):String;
	@:native("Code") public static function code(str:String):Int;
	@:native("Len") public static function len(str:String):Int;
	@:native("SplitCount") public static function splitCount(str:String, delimiter:String):Int;
	@:native("SplitIndex") public static function splitIndex(str:String, delimiter:String, index:Int):String;
	@:native("StripExt") public static function stripExt(filename:String):String;
	@:native("StripDir") public static function stripDir(filename:String):String;
	@:native("ExtractExt") public static function extractExt(filename:String):String;
	@:native("ExtractDir") public static function extractDir(filename:String):String;
	@:native("LoadString") public static function loadString(filename:String):String;
	@:native("SaveString") public static function saveString(str:String, filename:String, append:Bool):Void;
	@:native("CopyToClipboard") public static function copyToClipboard(str:String):Void;
	@:native("PasteFromClipboard") public static function pasteFromClipboard():String;
	@:native("AddSurface") public static function addSurface(mesh:Mesh, vertices:Memblock, numVertices:Int, indices:Memblock, numIndices:Int, type:Int):Surface;
	@:native("SetVertices") public static function setVertices(surface:Surface, vertices:Memblock, numVertices:Int):Void;
	@:native("NumVertices") public static function numVertices(surface:Surface):Int;
	@:native("VertexX") public static function vertexX(surface:Surface, index:Int):Float;
	@:native("VertexY") public static function vertexY(surface:Surface, index:Int):Float;
	@:native("VertexZ") public static function vertexZ(surface:Surface, index:Int):Float;
	@:native("VertexNX") public static function vertexNX(surface:Surface, index:Int):Float;
	@:native("VertexNY") public static function vertexNY(surface:Surface, index:Int):Float;
	@:native("VertexNZ") public static function vertexNZ(surface:Surface, index:Int):Float;
	@:native("VertexColor") public static function vertexColor(surface:Surface, index:Int):Int;
	@:native("VertexU") public static function vertexU(surface:Surface, index:Int, set:Int):Float;
	@:native("VertexV") public static function vertexV(surface:Surface, index:Int, set:Int):Float;
	@:native("SetIndices") public static function setIndices(surface:Surface, indices:Memblock, numIndices:Int):Void;
	@:native("NumIndices") public static function numIndices(surface:Surface):Int;
	@:native("SurfaceIndex") public static function surfaceIndex(surface:Surface, number:Int):Int;
	@:native("SurfaceMaterial") public static function surfaceMaterial(surface:Surface):Material;
	@:native("LoadTerrain") public static function loadTerrain(heightmap:String, width:Float, height:Float, depth:Float):Terrain;
	@:native("ScaleTerrainTexture") public static function scaleTerrainTexture(terrain:Terrain, scale1:Float, scale2:Float):Void;
	@:native("CreateTexture") public static function createTexture(width:Int, height:Int):Texture;
	@:native("CreateTextureFromPixmap") public static function createTextureFromPixmap(pixmap:Pixmap):Texture;
	@:native("CreateRenderTexture") public static function createRenderTexture(width:Int, height:Int):Texture;
	@:native("LoadTexture") public static function loadTexture(filename:String):Texture;
	@:native("ClearTextureCache") public static function clearTextureCache():Void;
	@:native("DrawTexture") public static function drawTexture(tex:Texture, x:Int, y:Int):Void;
	@:native("DrawTextureEx") public static function drawTextureEx(tex:Texture, x:Int, y:Int, width:Int, height:Int, color:Int):Void;
	@:native("DrawTextureEx2") public static function drawTextureEx2(tex:Texture, src_x:Int, src_y:Int, src_width:Int, src_height:Int, dst_x:Int, dst_y:Int, dst_width:Int, dst_height:Int, color:Int):Void;
	@:native("LockTexture") public static function lockTexture(tex:Texture):Void;
	@:native("UnlockTexture") public static function unlockTexture(tex:Texture):Void;
	@:native("SetTextureColorKey") public static function setTextureColorKey(tex:Texture, color:Int):Void;
	@:native("NormalizeTexture") public static function normalizeTexture(tex:Texture, amplitude:Float):Void;
	@:native("TextureWidth") public static function textureWidth(tex:Texture):Int;
	@:native("TextureHeight") public static function textureHeight(tex:Texture):Int;
	@:native("TextureFilename") public static function textureFilename(tex:Texture):String;
	@:native("SetTextureCreationFlags") public static function setTextureCreationFlags(flags:Int):Void;
	@:native("CreateWaterVolume") public static function createWaterVolume(width:Float, depth:Float, tiles_width:Int, tiles_depth:Int, wave_height:Float, wave_speed:Float, wave_length:Float):Entity;
	@:native("SetAmbient") public static function setAmbient(color:Int):Void;
	@:native("SetShadowColor") public static function setShadowColor(color:Int):Void;
	@:native("SetFog") public static function setFog(color:Int, near_:Float, far_:Float):Void;
	@:native("SetSkybox") public static function setSkybox(top:Texture, bottom:Texture, left:Texture, right:Texture, front:Texture, back:Texture):Void;
	@:native("SetSkydome") public static function setSkydome(tex:Texture, texScale:Float, fullSphere:Bool):Void;
	@:native("SkyboxMaterial") public static function skyboxMaterial():Material;
	@:native("SkydomeMaterial") public static function skydomeMaterial():Material;
	@:native("DrawWorld") public static function drawWorld():Void;
	@:native("WorldToScreen") public static function worldToScreen(camera:Camera, x:Float, y:Float, z:Float):Void;
	@:native("ScreenToWorld") public static function screenToWorld(camera:Camera, x:Int, y:Int, depth:Float):Void;
	@:native("Raycast") public static function raycast(x1:Float, y1:Float, z1:Float, x2:Float, y2:Float, z2:Float, group:Int):Entity;
}
