
#ifndef COLDSTEEL_SDK_H_INCLUDED
#define COLDSTEEL_SDK_H_INCLUDED

#ifdef __cplusplus
extern "C"
{
#endif

struct Camera;
typedef int Bool;
struct Texture;
struct Entity;
struct Material;
struct Font;
struct Light;
typedef void Memblock;
struct Mesh;
struct Surface;
struct Model;
struct Pixmap;
struct Sound;
typedef int Channel;
struct Sprite;
struct Terrain;
typedef int (*BitAndFunc)(int, int);
typedef int (*BitOrFunc)(int, int);
typedef int (*BitXorFunc)(int, int);
typedef int (*BitNotFunc)(int);
typedef int (*ShlFunc)(int, int);
typedef int (*ShrFunc)(int, int);
typedef Camera *(*CreateCameraFunc)();
typedef void (*SetCameraActiveFunc)(Camera *, Bool);
typedef Bool (*CameraActiveFunc)(Camera *);
typedef void (*SetCameraViewportFunc)(Camera *, int, int, int, int);
typedef int (*CameraViewportXFunc)(Camera *);
typedef int (*CameraViewportYFunc)(Camera *);
typedef int (*CameraViewportWidthFunc)(Camera *);
typedef int (*CameraViewportHeightFunc)(Camera *);
typedef void (*SetCameraClearModeFunc)(Camera *, Bool, Bool);
typedef Bool (*CameraClearColorEnabledFunc)(Camera *);
typedef Bool (*CameraClearDepthEnabledFunc)(Camera *);
typedef void (*SetCameraClearColorFunc)(Camera *, int);
typedef int (*CameraClearColorFunc)(Camera *);
typedef void (*SetCameraRenderTargetFunc)(Camera *, Texture *);
typedef Texture *(*CameraRenderTargetFunc)(Camera *);
typedef void (*SetCameraRangeFunc)(Camera *, float, float);
typedef float (*CameraNearRangeFunc)(Camera *);
typedef float (*CameraFarRangeFunc)(Camera *);
typedef void (*SetCameraAspectRatioFunc)(Camera *, float);
typedef float (*CameraAspectRatioFunc)(Camera *);
typedef void (*SetCameraFOVFunc)(Camera *, float);
typedef float (*CameraFOVFunc)(Camera *);
typedef void (*SetCameraOrthoFunc)(Camera *, Bool);
typedef Bool (*CameraOrthoFunc)(Camera *);
typedef Entity *(*PickEntityFunc)(Camera *, int, int, int);
typedef void (*StopChannelFunc)(Channel);
typedef void (*PauseChannelFunc)(Channel);
typedef void (*ResumeChannelFunc)(Channel);
typedef void (*SetChannel3DPositionFunc)(Channel, float, float, float);
typedef void (*SetChannelRadiusFunc)(Channel, float);
typedef void (*SetChannelPitchFunc)(Channel, float);
typedef void (*SetChannelVolumeFunc)(Channel, float);
typedef void (*SetChannelPanFunc)(Channel, float);
typedef Bool (*ChannelPlayingFunc)(Channel);
typedef int (*RGBFunc)(int, int, int);
typedef int (*RGBAFunc)(int, int, int, int);
typedef int (*RGBFFunc)(float, float, float);
typedef int (*RGBAFFunc)(float, float, float, float);
typedef int (*RedValFunc)(int);
typedef int (*GreenValFunc)(int);
typedef int (*BlueValFunc)(int);
typedef int (*AlphaValFunc)(int);
typedef float (*RedValFFunc)(int);
typedef float (*GreenValFFunc)(int);
typedef float (*BlueValFFunc)(int);
typedef float (*AlphaValFFunc)(int);
typedef int (*FadeColorFunc)(int, int);
typedef int (*MultiplyColorFunc)(int, float);
typedef int (*SwapColorFunc)(int);
typedef float (*DeltaTimeFunc)();
typedef int (*MillisecsFunc)();
typedef void (*ExitFunc)(int);
typedef int (*SystemFunc)(const char *);
typedef Bool (*AddZipFunc)(const char *);
typedef const char *(*DirContentsFunc)(const char *);
typedef void (*ChangeDirFunc)(const char *);
typedef const char *(*CurrentDirFunc)();
typedef Entity *(*CreateEntityFunc)();
typedef void (*FreeEntityFunc)(Entity *);
typedef int (*EntityTypeFunc)(Entity *);
typedef void (*SetEntityNameFunc)(Entity *, const char *);
typedef const char *(*EntityNameFunc)(Entity *);
typedef void (*SetEntityVisibleFunc)(Entity *, Bool);
typedef Bool (*EntityVisibleFunc)(Entity *);
typedef void (*SetEntityParentFunc)(Entity *, Entity *);
typedef Entity *(*EntityParentFunc)(Entity *);
typedef int (*EntityNumChildrenFunc)(Entity *);
typedef Entity *(*EntityChildFunc)(Entity *, int);
typedef void (*SetEntityPositionFunc)(Entity *, float, float, float);
typedef void (*MoveEntityFunc)(Entity *, float, float, float);
typedef Entity *(*SlideEntityFunc)(Entity *, float, float, float, float, float, float, int);
typedef void (*TranslateEntityFunc)(Entity *, float, float, float);
typedef float (*EntityXFunc)(Entity *);
typedef float (*EntityYFunc)(Entity *);
typedef float (*EntityZFunc)(Entity *);
typedef float (*EntityLocalXFunc)(Entity *);
typedef float (*EntityLocalYFunc)(Entity *);
typedef float (*EntityLocalZFunc)(Entity *);
typedef void (*SetEntityRotationFunc)(Entity *, float, float, float);
typedef void (*TurnEntityFunc)(Entity *, float, float, float);
typedef void (*PointEntityFunc)(Entity *, float, float, float);
typedef float (*EntityPitchFunc)(Entity *);
typedef float (*EntityYawFunc)(Entity *);
typedef float (*EntityRollFunc)(Entity *);
typedef void (*SetEntityScaleFunc)(Entity *, float, float, float);
typedef float (*EntityScaleXFunc)(Entity *);
typedef float (*EntityScaleYFunc)(Entity *);
typedef float (*EntityScaleZFunc)(Entity *);
typedef float (*EntityWidthFunc)(Entity *);
typedef float (*EntityHeightFunc)(Entity *);
typedef float (*EntityDepthFunc)(Entity *);
typedef int (*EntityNumMaterialsFunc)(Entity *);
typedef Material *(*EntityMaterialFunc)(Entity *, int);
typedef void (*SetEntityCollisionFunc)(Entity *, int, int);
typedef Bool (*EntityCollisionFunc)(Entity *);
typedef int (*EntityGroupFunc)(Entity *);
typedef float (*EntityDistanceFunc)(Entity *, float, float, float);
typedef float (*EntitySquareDistanceFunc)(Entity *, float, float, float);
typedef Font *(*LoadFontFunc)(const char *, int);
typedef void (*FreeFontFunc)(Font *);
typedef void (*DrawTextFunc)(Font *, const char *, int, int, int);
typedef int (*TextWidthFunc)(Font *, const char *);
typedef int (*TextHeightFunc)(Font *, const char *);
typedef void (*SetRenderTargetFunc)(Texture *, Bool, Bool, int);
typedef void (*SetViewportFunc)(int, int, int, int);
typedef void (*DrawPointFunc)(int, int, int);
typedef void (*DrawLineFunc)(int, int, int, int, int);
typedef void (*DrawRectFunc)(int, int, int, int, int);
typedef void (*Draw3DLineFunc)(float, float, float, float, float, float, int);
typedef void (*SetCursorVisibleFunc)(Bool);
typedef void (*SetCursorPositionFunc)(int, int);
typedef int (*CursorXFunc)();
typedef int (*CursorYFunc)();
typedef int (*CursorZFunc)();
typedef Bool (*ButtonDownFunc)(int);
typedef Bool (*ButtonHitFunc)(int);
typedef Bool (*KeyDownFunc)(int);
typedef Bool (*KeyHitFunc)(int);
typedef int (*NumJoysticksFunc)();
typedef const char *(*JoystickNameFunc)(int);
typedef int (*NumJoystickAxesFunc)(int);
typedef int (*NumJoystickButtonsFunc)(int);
typedef Bool (*JoystickButtonDownFunc)(int, int);
typedef float (*JoystickAxisFunc)(int, int);
typedef Light *(*CreateLightFunc)(int);
typedef int (*LightTypeFunc)(Light *);
typedef void (*SetLightDiffuseFunc)(Light *, int);
typedef int (*LightDiffuseFunc)(Light *);
typedef void (*SetLightAmbientFunc)(Light *, int);
typedef int (*LightAmbientFunc)(Light *);
typedef void (*SetLightSpecularFunc)(Light *, int);
typedef int (*LightSpecularFunc)(Light *);
typedef void (*SetLightCastShadowsFunc)(Light *, Bool);
typedef Bool (*LightCastShadowsFunc)(Light *);
typedef void (*SetLightRadiusFunc)(Light *, float);
typedef float (*LightRadiusFunc)(Light *);
typedef void (*SetLightAttenuationFunc)(Light *, float, float, float);
typedef float (*LightConstantAttenuationFunc)(Light *);
typedef float (*LightLinearAttenuationFunc)(Light *);
typedef float (*LightQuadraticAttenuationFunc)(Light *);
typedef void (*SetLightConeFunc)(Light *, float, float);
typedef float (*LightInnerConeFunc)(Light *);
typedef float (*LightOuterConeFunc)(Light *);
typedef void (*SetLightFalloffFunc)(Light *, float);
typedef float (*LightFalloffFunc)(Light *);
typedef void (*SetListenerFunc)(float, float, float, float);
typedef void (*LogInfoFunc)(const char *);
typedef void (*SetMaterialTextureFunc)(Material *, int, Texture *);
typedef Texture *(*MaterialTextureFunc)(Material *, int);
typedef void (*SetMaterialTextureTransformFunc)(Material *, int, float, float, float, float, float);
typedef void (*SetMaterialTypeFunc)(Material *, int);
typedef int (*MaterialTypeFunc)(Material *);
typedef void (*SetMaterialDiffuseFunc)(Material *, int);
typedef int (*MaterialDiffuseFunc)(Material *);
typedef void (*SetMaterialEmissiveFunc)(Material *, int);
typedef int (*MaterialEmissiveFunc)(Material *);
typedef void (*SetMaterialAmbientFunc)(Material *, int);
typedef int (*MaterialAmbientFunc)(Material *);
typedef void (*SetMaterialSpecularFunc)(Material *, int);
typedef int (*MaterialSpecularFunc)(Material *);
typedef void (*SetMaterialShininessFunc)(Material *, float);
typedef float (*MaterialShininessFunc)(Material *);
typedef void (*SetMaterialRenderModeFunc)(Material *, int);
typedef int (*MaterialRenderModeFunc)(Material *);
typedef void (*SetMaterialFilterModeFunc)(Material *, int);
typedef int (*MaterialFilterModeFunc)(Material *);
typedef void (*SetMaterialLightingModeFunc)(Material *, int);
typedef int (*MaterialLightingModeFunc)(Material *);
typedef void (*SetMaterialFlagFunc)(Material *, int, Bool);
typedef Bool (*MaterialFlagFunc)(Material *, int);
typedef float (*FloorFunc)(float);
typedef float (*CeilFunc)(float);
typedef float (*AbsFunc)(float);
typedef float (*SqrFunc)(float);
typedef float (*SinFunc)(float);
typedef float (*CosFunc)(float);
typedef float (*TanFunc)(float);
typedef float (*ASinFunc)(float);
typedef float (*ACosFunc)(float);
typedef float (*ATanFunc)(float);
typedef float (*ATan2Func)(float, float);
typedef float (*ExpFunc)(float);
typedef float (*PowFunc)(float, float);
typedef float (*LogFunc)(float);
typedef float (*Log10Func)(float);
typedef float (*MinFunc)(float, float);
typedef float (*MaxFunc)(float, float);
typedef float (*ClampFunc)(float, float, float);
typedef int (*BoolToIntFunc)(Bool);
typedef int (*IntFunc)(float);
typedef int (*RandFunc)(int, int);
typedef void (*RandSeedFunc)(int);
typedef float (*DegFunc)(float);
typedef float (*RadFunc)(float);
typedef float (*WrapFunc)(float, float);
typedef float (*PointXFunc)();
typedef float (*PointYFunc)();
typedef float (*PointZFunc)();
typedef float (*NormalXFunc)();
typedef float (*NormalYFunc)();
typedef float (*NormalZFunc)();
typedef Memblock *(*CreateMemblockFunc)(int);
typedef Memblock *(*LoadMemblockFunc)(const char *);
typedef void (*SaveMemblockFunc)(Memblock *, const char *);
typedef void (*FreeMemblockFunc)(Memblock *);
typedef int (*MemblockSizeFunc)(Memblock *);
typedef void (*PokeByteFunc)(Memblock *, int, int);
typedef void (*PokeShortFunc)(Memblock *, int, int);
typedef void (*PokeIntFunc)(Memblock *, int, int);
typedef void (*PokeFloatFunc)(Memblock *, int, float);
typedef void (*PokeStringFunc)(Memblock *, int, const char *);
typedef int (*PeekByteFunc)(Memblock *, int);
typedef int (*PeekShortFunc)(Memblock *, int);
typedef int (*PeekIntFunc)(Memblock *, int);
typedef float (*PeekFloatFunc)(Memblock *, int);
typedef const char *(*PeekStringFunc)(Memblock *, int);
typedef Mesh *(*CreateConeMeshFunc)(int);
typedef Mesh *(*CreateCubeMeshFunc)();
typedef Mesh *(*CreateCylinderMeshFunc)(int);
typedef Mesh *(*CreateMeshFunc)();
typedef Mesh *(*CreateQuadMeshFunc)();
typedef Mesh *(*CreateSimpleCubeMeshFunc)();
typedef Mesh *(*CreateSphereMeshFunc)(int);
typedef Mesh *(*LoadMeshFunc)(const char *);
typedef Mesh *(*LoadTerrainMeshFunc)(Pixmap *, Pixmap *, float, float, float);
typedef void (*FreeMeshFunc)(Mesh *);
typedef void (*SetMeshFPSFunc)(Mesh *, float);
typedef float (*MeshFPSFunc)(Mesh *);
typedef int (*MeshFramesFunc)(Mesh *);
typedef Mesh *(*MeshForFrameFunc)(Mesh *, int);
typedef int (*NumSurfacesFunc)(Mesh *);
typedef Surface *(*MeshSurfaceFunc)(Mesh *, int);
typedef void (*UpdateMeshFunc)(Mesh *);
typedef void (*TranslateMeshFunc)(Mesh *, float, float, float);
typedef void (*RotateMeshFunc)(Mesh *, float, float, float);
typedef void (*ScaleMeshFunc)(Mesh *, float, float, float);
typedef void (*FlipMeshFunc)(Mesh *);
typedef void (*SetMeshColorFunc)(Mesh *, int);
typedef void (*UpdateMeshNormalsFunc)(Mesh *);
typedef float (*MeshWidthFunc)(Mesh *);
typedef float (*MeshHeightFunc)(Mesh *);
typedef float (*MeshDepthFunc)(Mesh *);
typedef Model *(*CreateConeModelFunc)(int);
typedef Model *(*CreateCubeModelFunc)();
typedef Model *(*CreateCylinderModelFunc)(int);
typedef Model *(*CreateModelFunc)(Mesh *);
typedef Model *(*CreateOctreeModelFunc)(Mesh *);
typedef Model *(*CreateQuadModelFunc)();
typedef Model *(*CreateSphereModelFunc)(int);
typedef Model *(*LoadModelFunc)(const char *);
typedef Model *(*LoadOctreeModelFunc)(const char *);
typedef Mesh *(*ModelMeshFunc)(Model *);
typedef void (*SetModelCastShadowsFunc)(Model *, Bool);
typedef Bool (*ModelCastShadowsFunc)(Model *);
typedef void (*SetModelLoopFunc)(Model *, Bool);
typedef Bool (*ModelLoopFunc)(Model *);
typedef void (*SetModelFPSFunc)(Model *, float);
typedef float (*ModelFPSFunc)(Model *);
typedef void (*SetModelFrameFunc)(Model *, float);
typedef float (*ModelFrameFunc)(Model *);
typedef void (*SetModelFramesFunc)(Model *, int, int);
typedef int (*ModelFirstFrameFunc)(Model *);
typedef int (*ModelLastFrameFunc)(Model *);
typedef Bool (*PlayMusicFunc)(const char *, Bool);
typedef void (*StopMusicFunc)();
typedef void (*PauseMusicFunc)();
typedef void (*ResumeMusicFunc)();
typedef void (*SetMusicVolumeFunc)(float);
typedef Bool (*MusicPlayingFunc)();
typedef Pixmap *(*CreatePixmapFunc)(int, int);
typedef Pixmap *(*CreatePixmapFromTextureFunc)(Texture *);
typedef Pixmap *(*CreatePixmapFromScreenFunc)();
typedef Pixmap *(*LoadPixmapFunc)(const char *);
typedef void (*FreePixmapFunc)(Pixmap *);
typedef void (*SavePixmapFunc)(Pixmap *, const char *);
typedef int (*ReadPixelFunc)(Pixmap *, int, int);
typedef void (*WritePixelFunc)(Pixmap *, int, int, int);
typedef int (*PixmapWidthFunc)(Pixmap *);
typedef int (*PixmapHeightFunc)(Pixmap *);
typedef void (*SetDriverFunc)(int);
typedef const char *(*DriverNameFunc)();
typedef void (*OpenScreenFunc)(int, int, int, int);
typedef void (*OpenScreenExFunc)(int, int, int, int, int, void *);
typedef void (*CloseScreenFunc)();
typedef void (*ClearScreenFunc)(int);
typedef void (*RefreshScreenFunc)();
typedef void (*SetScreenTitleFunc)(const char *);
typedef void (*SetScreenSizeFunc)(int, int);
typedef Bool (*ScreenActiveFunc)();
typedef Bool (*ScreenShouldCloseFunc)();
typedef int (*ScreenWidthFunc)();
typedef int (*ScreenHeightFunc)();
typedef void (*SetScreenFPSFunc)(int);
typedef int (*ScreenFPSFunc)();
typedef int (*ScreenNumModesFunc)();
typedef int (*ScreenModeWidthFunc)(int);
typedef int (*ScreenModeHeightFunc)(int);
typedef int (*ScreenModeDepthFunc)(int);
typedef int (*DesktopWidthFunc)();
typedef int (*DesktopHeightFunc)();
typedef int (*DesktopDepthFunc)();
typedef void (*MinimizeWindowFunc)();
typedef void (*MaximizeWindowFunc)();
typedef void (*RestoreWindowFunc)();
typedef Sound *(*LoadSoundFunc)(const char *);
typedef void (*FreeSoundFunc)(Sound *);
typedef Channel (*PlaySoundFunc)(Sound *, Bool);
typedef Channel (*PlaySound3DFunc)(Sound *, float, float, float, float, Bool);
typedef Sprite *(*CreateSpriteFunc)(Texture *, int);
typedef void (*SetSpriteSizeFunc)(Sprite *, float, float);
typedef float (*SpriteWidthFunc)(Sprite *);
typedef float (*SpriteHeightFunc)(Sprite *);
typedef int (*ValFunc)(const char *);
typedef float (*ValFFunc)(const char *);
typedef const char *(*StrFunc)(int);
typedef const char *(*StrFFunc)(float);
typedef const char *(*LeftFunc)(const char *, int);
typedef const char *(*RightFunc)(const char *, int);
typedef const char *(*MidFunc)(const char *, int, int);
typedef const char *(*ReplaceFunc)(const char *, const char *, const char *);
typedef int (*FindFunc)(const char *, const char *, int);
typedef const char *(*UpperFunc)(const char *);
typedef const char *(*LowerFunc)(const char *);
typedef const char *(*TrimFunc)(const char *);
typedef const char *(*CharFunc)(int);
typedef int (*CodeFunc)(const char *);
typedef int (*LenFunc)(const char *);
typedef int (*SplitCountFunc)(const char *, const char *);
typedef const char *(*SplitIndexFunc)(const char *, const char *, int);
typedef const char *(*StripExtFunc)(const char *);
typedef const char *(*StripDirFunc)(const char *);
typedef const char *(*ExtractExtFunc)(const char *);
typedef const char *(*ExtractDirFunc)(const char *);
typedef const char *(*LoadStringFunc)(const char *);
typedef void (*SaveStringFunc)(const char *, const char *, Bool);
typedef void (*CopyToClipboardFunc)(const char *);
typedef const char *(*PasteFromClipboardFunc)();
typedef Surface *(*AddSurfaceFunc)(Mesh *, Memblock *, int, Memblock *, int, int);
typedef void (*SetVerticesFunc)(Surface *, Memblock *, int);
typedef int (*NumVerticesFunc)(Surface *);
typedef float (*VertexXFunc)(Surface *, int);
typedef float (*VertexYFunc)(Surface *, int);
typedef float (*VertexZFunc)(Surface *, int);
typedef float (*VertexNXFunc)(Surface *, int);
typedef float (*VertexNYFunc)(Surface *, int);
typedef float (*VertexNZFunc)(Surface *, int);
typedef int (*VertexColorFunc)(Surface *, int);
typedef float (*VertexUFunc)(Surface *, int, int);
typedef float (*VertexVFunc)(Surface *, int, int);
typedef void (*SetIndicesFunc)(Surface *, Memblock *, int);
typedef int (*NumIndicesFunc)(Surface *);
typedef int (*SurfaceIndexFunc)(Surface *, int);
typedef Material *(*SurfaceMaterialFunc)(Surface *);
typedef Terrain *(*LoadTerrainFunc)(const char *, float, float, float);
typedef void (*ScaleTerrainTextureFunc)(Terrain *, float, float);
typedef Texture *(*CreateTextureFunc)(int, int);
typedef Texture *(*CreateTextureFromPixmapFunc)(Pixmap *);
typedef Texture *(*CreateRenderTextureFunc)(int, int);
typedef Texture *(*LoadTextureFunc)(const char *);
typedef void (*ClearTextureCacheFunc)();
typedef void (*DrawTextureFunc)(Texture *, int, int);
typedef void (*DrawTextureExFunc)(Texture *, int, int, int, int, int);
typedef void (*DrawTextureEx2Func)(Texture *, int, int, int, int, int, int, int, int, int);
typedef void (*LockTextureFunc)(Texture *);
typedef void (*UnlockTextureFunc)(Texture *);
typedef void (*SetTextureColorKeyFunc)(Texture *, int);
typedef void (*NormalizeTextureFunc)(Texture *, float);
typedef int (*TextureWidthFunc)(Texture *);
typedef int (*TextureHeightFunc)(Texture *);
typedef const char *(*TextureFilenameFunc)(Texture *);
typedef void (*SetTextureCreationFlagsFunc)(int);
typedef Entity *(*CreateWaterVolumeFunc)(float, float, int, int, float, float, float);
typedef void (*SetAmbientFunc)(int);
typedef void (*SetShadowColorFunc)(int);
typedef void (*SetFogFunc)(int, float, float);
typedef void (*SetSkyboxFunc)(Texture *, Texture *, Texture *, Texture *, Texture *, Texture *);
typedef void (*SetSkydomeFunc)(Texture *, float, Bool);
typedef Material *(*SkyboxMaterialFunc)();
typedef Material *(*SkydomeMaterialFunc)();
typedef void (*DrawWorldFunc)();
typedef void (*WorldToScreenFunc)(Camera *, float, float, float);
typedef void (*ScreenToWorldFunc)(Camera *, int, int, float);
typedef Entity *(*RaycastFunc)(float, float, float, float, float, float, int);

  typedef struct
  {
    void (*RegisterFunction)(const char *name, int (*f)(void *));
    int (*GetBoolArg)(void *context, int index);
    int (*GetIntArg)(void *context, int index);
    float (*GetFloatArg)(void *context, int index);
    const char *(*GetStringArg)(void *context, int index);
    const void *(*GetPointerArg)(void *context, int index);
    void (*PushBool)(void *context, int val);
    void (*PushInt)(void *context, int val);
    void (*PushFloat)(void *context, float val);
    void (*PushString)(void *context, const char *val);
    void (*PushPointer)(void *context, void *val);
    BitAndFunc BitAnd;
    BitOrFunc BitOr;
    BitXorFunc BitXor;
    BitNotFunc BitNot;
    ShlFunc Shl;
    ShrFunc Shr;
    CreateCameraFunc CreateCamera;
    SetCameraActiveFunc SetCameraActive;
    CameraActiveFunc CameraActive;
    SetCameraViewportFunc SetCameraViewport;
    CameraViewportXFunc CameraViewportX;
    CameraViewportYFunc CameraViewportY;
    CameraViewportWidthFunc CameraViewportWidth;
    CameraViewportHeightFunc CameraViewportHeight;
    SetCameraClearModeFunc SetCameraClearMode;
    CameraClearColorEnabledFunc CameraClearColorEnabled;
    CameraClearDepthEnabledFunc CameraClearDepthEnabled;
    SetCameraClearColorFunc SetCameraClearColor;
    CameraClearColorFunc CameraClearColor;
    SetCameraRenderTargetFunc SetCameraRenderTarget;
    CameraRenderTargetFunc CameraRenderTarget;
    SetCameraRangeFunc SetCameraRange;
    CameraNearRangeFunc CameraNearRange;
    CameraFarRangeFunc CameraFarRange;
    SetCameraAspectRatioFunc SetCameraAspectRatio;
    CameraAspectRatioFunc CameraAspectRatio;
    SetCameraFOVFunc SetCameraFOV;
    CameraFOVFunc CameraFOV;
    SetCameraOrthoFunc SetCameraOrtho;
    CameraOrthoFunc CameraOrtho;
    PickEntityFunc PickEntity;
    StopChannelFunc StopChannel;
    PauseChannelFunc PauseChannel;
    ResumeChannelFunc ResumeChannel;
    SetChannel3DPositionFunc SetChannel3DPosition;
    SetChannelRadiusFunc SetChannelRadius;
    SetChannelPitchFunc SetChannelPitch;
    SetChannelVolumeFunc SetChannelVolume;
    SetChannelPanFunc SetChannelPan;
    ChannelPlayingFunc ChannelPlaying;
    RGBFunc RGB;
    RGBAFunc RGBA;
    RGBFFunc RGBF;
    RGBAFFunc RGBAF;
    RedValFunc RedVal;
    GreenValFunc GreenVal;
    BlueValFunc BlueVal;
    AlphaValFunc AlphaVal;
    RedValFFunc RedValF;
    GreenValFFunc GreenValF;
    BlueValFFunc BlueValF;
    AlphaValFFunc AlphaValF;
    FadeColorFunc FadeColor;
    MultiplyColorFunc MultiplyColor;
    SwapColorFunc SwapColor;
    DeltaTimeFunc DeltaTime;
    MillisecsFunc Millisecs;
    ExitFunc Exit;
    SystemFunc System;
    AddZipFunc AddZip;
    DirContentsFunc DirContents;
    ChangeDirFunc ChangeDir;
    CurrentDirFunc CurrentDir;
    CreateEntityFunc CreateEntity;
    FreeEntityFunc FreeEntity;
    EntityTypeFunc EntityType;
    SetEntityNameFunc SetEntityName;
    EntityNameFunc EntityName;
    SetEntityVisibleFunc SetEntityVisible;
    EntityVisibleFunc EntityVisible;
    SetEntityParentFunc SetEntityParent;
    EntityParentFunc EntityParent;
    EntityNumChildrenFunc EntityNumChildren;
    EntityChildFunc EntityChild;
    SetEntityPositionFunc SetEntityPosition;
    MoveEntityFunc MoveEntity;
    SlideEntityFunc SlideEntity;
    TranslateEntityFunc TranslateEntity;
    EntityXFunc EntityX;
    EntityYFunc EntityY;
    EntityZFunc EntityZ;
    EntityLocalXFunc EntityLocalX;
    EntityLocalYFunc EntityLocalY;
    EntityLocalZFunc EntityLocalZ;
    SetEntityRotationFunc SetEntityRotation;
    TurnEntityFunc TurnEntity;
    PointEntityFunc PointEntity;
    EntityPitchFunc EntityPitch;
    EntityYawFunc EntityYaw;
    EntityRollFunc EntityRoll;
    SetEntityScaleFunc SetEntityScale;
    EntityScaleXFunc EntityScaleX;
    EntityScaleYFunc EntityScaleY;
    EntityScaleZFunc EntityScaleZ;
    EntityWidthFunc EntityWidth;
    EntityHeightFunc EntityHeight;
    EntityDepthFunc EntityDepth;
    EntityNumMaterialsFunc EntityNumMaterials;
    EntityMaterialFunc EntityMaterial;
    SetEntityCollisionFunc SetEntityCollision;
    EntityCollisionFunc EntityCollision;
    EntityGroupFunc EntityGroup;
    EntityDistanceFunc EntityDistance;
    EntitySquareDistanceFunc EntitySquareDistance;
    LoadFontFunc LoadFont;
    FreeFontFunc FreeFont;
    DrawTextFunc DrawText;
    TextWidthFunc TextWidth;
    TextHeightFunc TextHeight;
    SetRenderTargetFunc SetRenderTarget;
    SetViewportFunc SetViewport;
    DrawPointFunc DrawPoint;
    DrawLineFunc DrawLine;
    DrawRectFunc DrawRect;
    Draw3DLineFunc Draw3DLine;
    SetCursorVisibleFunc SetCursorVisible;
    SetCursorPositionFunc SetCursorPosition;
    CursorXFunc CursorX;
    CursorYFunc CursorY;
    CursorZFunc CursorZ;
    ButtonDownFunc ButtonDown;
    ButtonHitFunc ButtonHit;
    KeyDownFunc KeyDown;
    KeyHitFunc KeyHit;
    NumJoysticksFunc NumJoysticks;
    JoystickNameFunc JoystickName;
    NumJoystickAxesFunc NumJoystickAxes;
    NumJoystickButtonsFunc NumJoystickButtons;
    JoystickButtonDownFunc JoystickButtonDown;
    JoystickAxisFunc JoystickAxis;
    CreateLightFunc CreateLight;
    LightTypeFunc LightType;
    SetLightDiffuseFunc SetLightDiffuse;
    LightDiffuseFunc LightDiffuse;
    SetLightAmbientFunc SetLightAmbient;
    LightAmbientFunc LightAmbient;
    SetLightSpecularFunc SetLightSpecular;
    LightSpecularFunc LightSpecular;
    SetLightCastShadowsFunc SetLightCastShadows;
    LightCastShadowsFunc LightCastShadows;
    SetLightRadiusFunc SetLightRadius;
    LightRadiusFunc LightRadius;
    SetLightAttenuationFunc SetLightAttenuation;
    LightConstantAttenuationFunc LightConstantAttenuation;
    LightLinearAttenuationFunc LightLinearAttenuation;
    LightQuadraticAttenuationFunc LightQuadraticAttenuation;
    SetLightConeFunc SetLightCone;
    LightInnerConeFunc LightInnerCone;
    LightOuterConeFunc LightOuterCone;
    SetLightFalloffFunc SetLightFalloff;
    LightFalloffFunc LightFalloff;
    SetListenerFunc SetListener;
    LogInfoFunc LogInfo;
    SetMaterialTextureFunc SetMaterialTexture;
    MaterialTextureFunc MaterialTexture;
    SetMaterialTextureTransformFunc SetMaterialTextureTransform;
    SetMaterialTypeFunc SetMaterialType;
    MaterialTypeFunc MaterialType;
    SetMaterialDiffuseFunc SetMaterialDiffuse;
    MaterialDiffuseFunc MaterialDiffuse;
    SetMaterialEmissiveFunc SetMaterialEmissive;
    MaterialEmissiveFunc MaterialEmissive;
    SetMaterialAmbientFunc SetMaterialAmbient;
    MaterialAmbientFunc MaterialAmbient;
    SetMaterialSpecularFunc SetMaterialSpecular;
    MaterialSpecularFunc MaterialSpecular;
    SetMaterialShininessFunc SetMaterialShininess;
    MaterialShininessFunc MaterialShininess;
    SetMaterialRenderModeFunc SetMaterialRenderMode;
    MaterialRenderModeFunc MaterialRenderMode;
    SetMaterialFilterModeFunc SetMaterialFilterMode;
    MaterialFilterModeFunc MaterialFilterMode;
    SetMaterialLightingModeFunc SetMaterialLightingMode;
    MaterialLightingModeFunc MaterialLightingMode;
    SetMaterialFlagFunc SetMaterialFlag;
    MaterialFlagFunc MaterialFlag;
    FloorFunc Floor;
    CeilFunc Ceil;
    AbsFunc Abs;
    SqrFunc Sqr;
    SinFunc Sin;
    CosFunc Cos;
    TanFunc Tan;
    ASinFunc ASin;
    ACosFunc ACos;
    ATanFunc ATan;
    ATan2Func ATan2;
    ExpFunc Exp;
    PowFunc Pow;
    LogFunc Log;
    Log10Func Log10;
    MinFunc Min;
    MaxFunc Max;
    ClampFunc Clamp;
    BoolToIntFunc BoolToInt;
    IntFunc Int;
    RandFunc Rand;
    RandSeedFunc RandSeed;
    DegFunc Deg;
    RadFunc Rad;
    WrapFunc Wrap;
    PointXFunc PointX;
    PointYFunc PointY;
    PointZFunc PointZ;
    NormalXFunc NormalX;
    NormalYFunc NormalY;
    NormalZFunc NormalZ;
    CreateMemblockFunc CreateMemblock;
    LoadMemblockFunc LoadMemblock;
    SaveMemblockFunc SaveMemblock;
    FreeMemblockFunc FreeMemblock;
    MemblockSizeFunc MemblockSize;
    PokeByteFunc PokeByte;
    PokeShortFunc PokeShort;
    PokeIntFunc PokeInt;
    PokeFloatFunc PokeFloat;
    PokeStringFunc PokeString;
    PeekByteFunc PeekByte;
    PeekShortFunc PeekShort;
    PeekIntFunc PeekInt;
    PeekFloatFunc PeekFloat;
    PeekStringFunc PeekString;
    CreateConeMeshFunc CreateConeMesh;
    CreateCubeMeshFunc CreateCubeMesh;
    CreateCylinderMeshFunc CreateCylinderMesh;
    CreateMeshFunc CreateMesh;
    CreateQuadMeshFunc CreateQuadMesh;
    CreateSimpleCubeMeshFunc CreateSimpleCubeMesh;
    CreateSphereMeshFunc CreateSphereMesh;
    LoadMeshFunc LoadMesh;
    LoadTerrainMeshFunc LoadTerrainMesh;
    FreeMeshFunc FreeMesh;
    SetMeshFPSFunc SetMeshFPS;
    MeshFPSFunc MeshFPS;
    MeshFramesFunc MeshFrames;
    MeshForFrameFunc MeshForFrame;
    NumSurfacesFunc NumSurfaces;
    MeshSurfaceFunc MeshSurface;
    UpdateMeshFunc UpdateMesh;
    TranslateMeshFunc TranslateMesh;
    RotateMeshFunc RotateMesh;
    ScaleMeshFunc ScaleMesh;
    FlipMeshFunc FlipMesh;
    SetMeshColorFunc SetMeshColor;
    UpdateMeshNormalsFunc UpdateMeshNormals;
    MeshWidthFunc MeshWidth;
    MeshHeightFunc MeshHeight;
    MeshDepthFunc MeshDepth;
    CreateConeModelFunc CreateConeModel;
    CreateCubeModelFunc CreateCubeModel;
    CreateCylinderModelFunc CreateCylinderModel;
    CreateModelFunc CreateModel;
    CreateOctreeModelFunc CreateOctreeModel;
    CreateQuadModelFunc CreateQuadModel;
    CreateSphereModelFunc CreateSphereModel;
    LoadModelFunc LoadModel;
    LoadOctreeModelFunc LoadOctreeModel;
    ModelMeshFunc ModelMesh;
    SetModelCastShadowsFunc SetModelCastShadows;
    ModelCastShadowsFunc ModelCastShadows;
    SetModelLoopFunc SetModelLoop;
    ModelLoopFunc ModelLoop;
    SetModelFPSFunc SetModelFPS;
    ModelFPSFunc ModelFPS;
    SetModelFrameFunc SetModelFrame;
    ModelFrameFunc ModelFrame;
    SetModelFramesFunc SetModelFrames;
    ModelFirstFrameFunc ModelFirstFrame;
    ModelLastFrameFunc ModelLastFrame;
    PlayMusicFunc PlayMusic;
    StopMusicFunc StopMusic;
    PauseMusicFunc PauseMusic;
    ResumeMusicFunc ResumeMusic;
    SetMusicVolumeFunc SetMusicVolume;
    MusicPlayingFunc MusicPlaying;
    CreatePixmapFunc CreatePixmap;
    CreatePixmapFromTextureFunc CreatePixmapFromTexture;
    CreatePixmapFromScreenFunc CreatePixmapFromScreen;
    LoadPixmapFunc LoadPixmap;
    FreePixmapFunc FreePixmap;
    SavePixmapFunc SavePixmap;
    ReadPixelFunc ReadPixel;
    WritePixelFunc WritePixel;
    PixmapWidthFunc PixmapWidth;
    PixmapHeightFunc PixmapHeight;
    SetDriverFunc SetDriver;
    DriverNameFunc DriverName;
    OpenScreenFunc OpenScreen;
    OpenScreenExFunc OpenScreenEx;
    CloseScreenFunc CloseScreen;
    ClearScreenFunc ClearScreen;
    RefreshScreenFunc RefreshScreen;
    SetScreenTitleFunc SetScreenTitle;
    SetScreenSizeFunc SetScreenSize;
    ScreenActiveFunc ScreenActive;
    ScreenShouldCloseFunc ScreenShouldClose;
    ScreenWidthFunc ScreenWidth;
    ScreenHeightFunc ScreenHeight;
    SetScreenFPSFunc SetScreenFPS;
    ScreenFPSFunc ScreenFPS;
    ScreenNumModesFunc ScreenNumModes;
    ScreenModeWidthFunc ScreenModeWidth;
    ScreenModeHeightFunc ScreenModeHeight;
    ScreenModeDepthFunc ScreenModeDepth;
    DesktopWidthFunc DesktopWidth;
    DesktopHeightFunc DesktopHeight;
    DesktopDepthFunc DesktopDepth;
    MinimizeWindowFunc MinimizeWindow;
    MaximizeWindowFunc MaximizeWindow;
    RestoreWindowFunc RestoreWindow;
    LoadSoundFunc LoadSound;
    FreeSoundFunc FreeSound;
    PlaySoundFunc PlaySound;
    PlaySound3DFunc PlaySound3D;
    CreateSpriteFunc CreateSprite;
    SetSpriteSizeFunc SetSpriteSize;
    SpriteWidthFunc SpriteWidth;
    SpriteHeightFunc SpriteHeight;
    ValFunc Val;
    ValFFunc ValF;
    StrFunc Str;
    StrFFunc StrF;
    LeftFunc Left;
    RightFunc Right;
    MidFunc Mid;
    ReplaceFunc Replace;
    FindFunc Find;
    UpperFunc Upper;
    LowerFunc Lower;
    TrimFunc Trim;
    CharFunc Char;
    CodeFunc Code;
    LenFunc Len;
    SplitCountFunc SplitCount;
    SplitIndexFunc SplitIndex;
    StripExtFunc StripExt;
    StripDirFunc StripDir;
    ExtractExtFunc ExtractExt;
    ExtractDirFunc ExtractDir;
    LoadStringFunc LoadString;
    SaveStringFunc SaveString;
    CopyToClipboardFunc CopyToClipboard;
    PasteFromClipboardFunc PasteFromClipboard;
    AddSurfaceFunc AddSurface;
    SetVerticesFunc SetVertices;
    NumVerticesFunc NumVertices;
    VertexXFunc VertexX;
    VertexYFunc VertexY;
    VertexZFunc VertexZ;
    VertexNXFunc VertexNX;
    VertexNYFunc VertexNY;
    VertexNZFunc VertexNZ;
    VertexColorFunc VertexColor;
    VertexUFunc VertexU;
    VertexVFunc VertexV;
    SetIndicesFunc SetIndices;
    NumIndicesFunc NumIndices;
    SurfaceIndexFunc SurfaceIndex;
    SurfaceMaterialFunc SurfaceMaterial;
    LoadTerrainFunc LoadTerrain;
    ScaleTerrainTextureFunc ScaleTerrainTexture;
    CreateTextureFunc CreateTexture;
    CreateTextureFromPixmapFunc CreateTextureFromPixmap;
    CreateRenderTextureFunc CreateRenderTexture;
    LoadTextureFunc LoadTexture;
    ClearTextureCacheFunc ClearTextureCache;
    DrawTextureFunc DrawTexture;
    DrawTextureExFunc DrawTextureEx;
    DrawTextureEx2Func DrawTextureEx2;
    LockTextureFunc LockTexture;
    UnlockTextureFunc UnlockTexture;
    SetTextureColorKeyFunc SetTextureColorKey;
    NormalizeTextureFunc NormalizeTexture;
    TextureWidthFunc TextureWidth;
    TextureHeightFunc TextureHeight;
    TextureFilenameFunc TextureFilename;
    SetTextureCreationFlagsFunc SetTextureCreationFlags;
    CreateWaterVolumeFunc CreateWaterVolume;
    SetAmbientFunc SetAmbient;
    SetShadowColorFunc SetShadowColor;
    SetFogFunc SetFog;
    SetSkyboxFunc SetSkybox;
    SetSkydomeFunc SetSkydome;
    SkyboxMaterialFunc SkyboxMaterial;
    SkydomeMaterialFunc SkydomeMaterial;
    DrawWorldFunc DrawWorld;
    WorldToScreenFunc WorldToScreen;
    ScreenToWorldFunc ScreenToWorld;
    RaycastFunc Raycast;
} ColdSteelSDK;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* COLDSTEEL_SDK_H_INCLUDED */
